# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: New Version Release

on:
  push:
    tags: 
      - '**'

jobs:
  apply-version-number-to-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm version ${GITHUB_REF#refs/*/} --no-git-tag-version
      - run: git add .
      - run: git commit -m"upgrade version number ${GITHUB_REF#refs/*/}"
      - run: git push origin/main
  

  publish-npm:
    runs-on: ubuntu-latest
    needs: [apply-version-number-to-code]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
          
  publish-homebrew:
    runs-on: ubuntu@latest
    steps:
      - run: echo "homebrew formula update for ${GITHUB_REF#refs/*/}"
